# Generated by Django 5.2.5 on 2025-11-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('total_solved', models.IntegerField(default=0)),
                ('easy_solved', models.IntegerField(default=0)),
                ('medium_solved', models.IntegerField(default=0)),
                ('hard_solved', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('contest_rating', models.FloatField(blank=True, null=True)),
                ('first_tracked', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-view_count', '-total_solved'],
                'indexes': [models.Index(fields=['-view_count'], name='tracker_tra_view_co_8af287_idx'), models.Index(fields=['-total_solved'], name='tracker_tra_total_s_44fc41_idx')],
            },
        ),
    ]
