# Generated by Django 5.2.5 on 2025-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeduser',
            name='last_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
