# Generated by GitHub Copilot on behalf of fix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackeduser_last_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeduser',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackeduser',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
